baseURL = "https://tammynpm.github.io/"
title = "tammy"
languageCode = "en-us"
theme = "researcher"

# Theme-specific global toggles
enableEmoji = true
math = false

# Build
enableRobotsTXT = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    id = ""

[params]
  author = "tammy"
  description = "tammy's corner"
  keywords = ["blog", "portfolio", "writeups", "ctf"]
  footer_text= "Copyright Â© 2025 Tammy Nguyen"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5


[menu]
  [[menu.main]]
    name = "CTFs"
    url = "/ctf/"
    weight = 1
  [[menu.main]]
    name = "Napkins"
    url = "/napkins/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2